<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="songapp.sqlite" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
		<PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <EditorConfigFiles Remove="C:\Users\nagoya-study049\source\repos\kensyuu\SampleApp001\.editorconfig" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="C:\Users\nagoya-study049\source\repos\kensyuu\SampleApp001\.editorconfig" />
	</ItemGroup>
</Project>